# Generated by Django 5.2.16 on 2026-07-28 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0016_smtp_e_historial_envios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaPolitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('contenido', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='normas/')),
                ('publicada_en', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'norma o política',
                'verbose_name_plural': 'normas y políticas',
                'ordering': ['-publicada_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'personal', 'verbose_name_plural': 'personal'},
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_personal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionturno',
            name='codigo',
            field=models.CharField(blank=True, choices=[('M', 'Mañana (7-15h)'), ('T', 'Tarde (15-23h)'), ('N', 'Noche (23-7h)'), ('F', 'Franco'), ('L', 'Licencia'), ('V', 'Vacaciones')], max_length=1),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('Enfermero/a', 'Enfermero/a'), ('Cuidador/a', 'Cuidador/a'), ('Mucama', 'Mucama'), ('Cocinero/a', 'Cocinero/a'), ('Administrativo/a', 'Administrativo/a'), ('Otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dni',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'El DNI solo puede contener números.')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Licencia', 'Licencia'), ('Vacaciones', 'Vacaciones'), ('Baja', 'Baja')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', 'El teléfono solo puede contener números.')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='turno_habitual',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=10),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=1)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completada', 'Completada')], default='Pendiente', max_length=15)),
                ('observacion_completado', models.TextField(blank=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('asignada_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='institucional.personal')),
                ('completada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_completadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['fecha', 'turno', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='LecturaNormaPolitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido_en', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_normas', to='institucional.personal')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='institucional.normapolitica')),
            ],
            options={
                'verbose_name': 'lectura de norma',
                'verbose_name_plural': 'lecturas de normas',
                'constraints': [models.UniqueConstraint(fields=('norma', 'personal'), name='lectura_norma_unica_por_personal')],
            },
        ),
    ]
