# Generated by Django 5.2.16 on 2026-07-28 19:18

import django.db.models.deletion
import institucional.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0017_normapolitica_alter_personal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('vence_en', models.DateTimeField(default=institucional.models.vencimiento_invitacion)),
                ('utilizada_en', models.DateTimeField(blank=True, null=True)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitacion', to='institucional.personal')),
            ],
            options={
                'verbose_name': 'invitación de personal',
                'verbose_name_plural': 'invitaciones de personal',
            },
        ),
    ]
