# Generated by Django 5.2.16 on 2026-07-30 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0019_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='contacto_familiar',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-zÁÉÍÓÚáéíóúÑñÜü' -]+$", 'Ingrese nombre y apellido, sin números ni símbolos.')]),
        ),
    ]
