# Generated by Django 5.2.16 on 2026-07-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0020_alter_residente_contacto_familiar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='smtp_contrasena',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='smtp_nombre_remitente',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='smtp_puerto',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='smtp_remitente',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='smtp_servidor',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='smtp_ssl',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='smtp_tls',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='smtp_usuario',
        ),
    ]
