# Generated by Django 5.2.16 on 2026-07-31 17:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0021_remove_configuracioninstitucional_smtp_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajacierre',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
