# Generated by Django 5.2.16 on 2026-07-31 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0022_cajacierre_resultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cajacierre',
            name='geriatrico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to='institucional.geriatrico'),
        ),
        migrations.AlterField(
            model_name='cajacierre',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='cajacierre',
            constraint=models.UniqueConstraint(fields=('fecha', 'geriatrico'), name='cierre_unico_por_geriatrico_y_mes'),
        ),
    ]
