# Generated by Django 5.2.16 on 2026-08-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0023_cajacierre_geriatrico_alter_cajacierre_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajamovimiento',
            name='geriatrico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='institucional.geriatrico'),
        ),
    ]
