# Generated by Django 5.2.16 on 2026-08-25

import django.db.models.deletion
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institucional", "0024_alter_cajamovimiento_geriatrico"),
    ]

    operations = [
        migrations.CreateModel(
            name="GastoRecurrente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("concepto", models.CharField(max_length=180)),
                ("importe_estimado", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("dia_vencimiento", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ("activo", models.BooleanField(default=True)),
                ("observaciones", models.TextField(blank=True)),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="gastos_recurrentes", to="institucional.categoriacaja")),
                ("geriatrico", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="gastos_recurrentes", to="institucional.geriatrico")),
            ],
            options={"verbose_name": "gasto recurrente", "verbose_name_plural": "gastos recurrentes", "ordering": ["concepto"]},
        ),
        migrations.CreateModel(
            name="GastoRecurrenteMensual",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("periodo", models.CharField(max_length=7)),
                ("concepto", models.CharField(max_length=180)),
                ("importe_estimado", models.DecimalField(decimal_places=2, max_digits=12)),
                ("importe_real", models.DecimalField(decimal_places=2, max_digits=12)),
                ("dia_vencimiento", models.PositiveSmallIntegerField()),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_pago", models.DateField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="institucional.categoriacaja")),
                ("gasto_recurrente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="historial_mensual", to="institucional.gastorecurrente")),
                ("geriatrico", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="gastos_recurrentes_mensuales", to="institucional.geriatrico")),
                ("movimiento_caja", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="gasto_recurrente_mensual", to="institucional.cajamovimiento")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "pago mensual de gasto recurrente", "verbose_name_plural": "pagos mensuales de gastos recurrentes", "ordering": ["-periodo", "concepto"]},
        ),
        migrations.AddConstraint(
            model_name="gastorecurrentemensual",
            constraint=models.UniqueConstraint(fields=("gasto_recurrente", "periodo"), name="gasto_recurrente_unico_por_periodo"),
        ),
    ]
