# Generated by Django 5.2.16 on 2026-08-25 20:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0026_adelantosueldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='geriatrico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='institucional.geriatrico'),
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('prioridad', models.CharField(choices=[('Normal', 'Normal'), ('Importante', 'Importante'), ('Urgente', 'Urgente')], default='Normal', max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('geriatrico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to='institucional.geriatrico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comunicado',
                'verbose_name_plural': 'comunicados',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LecturaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido_en', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='institucional.comunicado')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_comunicados', to='institucional.personal')),
            ],
            options={
                'verbose_name': 'lectura de comunicado',
                'verbose_name_plural': 'lecturas de comunicados',
                'constraints': [models.UniqueConstraint(fields=('comunicado', 'personal'), name='lectura_comunicado_unica_por_personal')],
            },
        ),
    ]
