from django.contrib.auth import views as auth_views
from django.urls import path
from .views import AcercaSistemaView, ActivarCuentaView, AdelantoSueldoCreateView, AdelantoSueldoListView, AdelantoSueldoUpdateView, AjusteMontoView, BackupView, CajaCierreView, CajaListView, CategoriaCajaListView, ComunicadoCreateView, ComunicadoLecturasView, ComunicadoMarcarLeidoView, ComunicadosListView, ComunicadoUpdateView, CierresCajaListView, ConfiguracionView, DescargarCierreCajaView, DescargarComprobanteView, EgresoCajaCreateView, EgresoCajaUpdateView, EnviarComprobanteView, EnviarEstadoCuentaView, ExportarCajaView, ExportarPagosView, ExportarPersonalView, ExportarResidentesView, ExportarTurnosView, GastosRecurrentesListView, GastoRecurrenteCreateView, GastoRecurrenteUpdateView, GenerarCuotasView, GeriatricoCreateView, GeriatricoDeleteView, GeriatricoListView, GeriatricoUpdateView, InicioView, MiPerfilView, MisTurnosView, NormaMarcarLeidaView, NormasListView, NotificacionesView, PagarGastoRecurrenteView, PagoDetailView, PagoListView, PanelTareasAdminView, PersonalCreateView, PersonalListView, PlanillaControlResidentesView, PlanillaFirmaEmpleadasView, PlanillasView, ResidenteCreateView, ResidenteDetailView, ResidenteListView, ServiceWorkerView, TareaCompletarView, TareaCreateView, TareaEnProcesoView, TareaUpdateView, TareasListView, TurnosView

urlpatterns = [
    path("service-worker.js", ServiceWorkerView.as_view(), name="service_worker"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("activar-cuenta/<uuid:token>/", ActivarCuentaView.as_view(), name="activar_cuenta"),
    path("mi-perfil/", MiPerfilView.as_view(), name="mi_perfil"),
    path("mis-turnos/", MisTurnosView.as_view(), name="mis_turnos"),
    path("notificaciones/", NotificacionesView.as_view(), name="notificaciones"),
    path("acerca-del-sistema/", AcercaSistemaView.as_view(), name="acerca_sistema"),
    path("planillas/", PlanillasView.as_view(), name="planillas"),
    path("planillas/control-residentes/", PlanillaControlResidentesView.as_view(), name="planilla_control_residentes"),
    path("planillas/firma-empleadas/", PlanillaFirmaEmpleadasView.as_view(), name="planilla_firma_empleadas"),
    path("", InicioView.as_view(), name="inicio"),
    path("residentes/", ResidenteListView.as_view(), name="residente_list"),
    path("residentes/nuevo/", ResidenteCreateView.as_view(), name="residente_create"),
    path("residentes/exportar/<str:formato>/", ExportarResidentesView.as_view(), name="residente_exportar"),
    path("residentes/<int:pk>/", ResidenteDetailView.as_view(), name="residente_detail"),
    path("pagos/", PagoListView.as_view(), name="pago_list"),
    path("pagos/exportar/<str:formato>/", ExportarPagosView.as_view(), name="pago_exportar"),
    path("pagos/generar-cuotas/", GenerarCuotasView.as_view(), name="generar_cuotas"),
    path("pagos/ajustar-montos/", AjusteMontoView.as_view(), name="ajuste_montos"),
    path("pagos/<int:pk>/", PagoDetailView.as_view(), name="pago_detail"),
    path("pagos/<int:pk>/enviar-comprobante/", EnviarComprobanteView.as_view(), name="enviar_comprobante"),
    path("pagos/<int:pk>/comprobante.pdf", DescargarComprobanteView.as_view(), name="descargar_comprobante"),
    path("residentes/<int:pk>/enviar-estado/", EnviarEstadoCuentaView.as_view(), name="enviar_estado_cuenta"),
    path("caja/", CajaListView.as_view(), name="caja_list"),
    path("caja/exportar/<str:formato>/", ExportarCajaView.as_view(), name="caja_exportar"),
    path("caja/egresos/nuevo/", EgresoCajaCreateView.as_view(), name="egreso_create"),
    path("caja/egresos/<int:pk>/editar/", EgresoCajaUpdateView.as_view(), name="egreso_update"),
    path("caja/gastos-recurrentes/", GastosRecurrentesListView.as_view(), name="gasto_recurrente_list"),
    path("caja/gastos-recurrentes/nuevo/", GastoRecurrenteCreateView.as_view(), name="gasto_recurrente_create"),
    path("caja/gastos-recurrentes/<int:pk>/editar/", GastoRecurrenteUpdateView.as_view(), name="gasto_recurrente_update"),
    path("caja/gastos-recurrentes/<int:pk>/pagar/", PagarGastoRecurrenteView.as_view(), name="gasto_recurrente_pagar"),
    path("caja/categorias/", CategoriaCajaListView.as_view(), name="categoria_caja_list"),
    path("caja/cerrar/", CajaCierreView.as_view(), name="caja_cierre"),
    path("caja/cierres/", CierresCajaListView.as_view(), name="caja_cierres"),
    path("caja/cierres/<int:pk>/pdf/", DescargarCierreCajaView.as_view(), name="caja_cierre_pdf"),
    path("configuracion/", ConfiguracionView.as_view(), name="configuracion"),
    path("configuracion/backup/", BackupView.as_view(), name="backup_generar"),
    path("tareas/", TareasListView.as_view(), name="tarea_list"),
    path("tareas/nueva/", TareaCreateView.as_view(), name="tarea_create"),
    path("tareas/<int:pk>/editar/", TareaUpdateView.as_view(), name="tarea_update"),
    path("tareas/panel/", PanelTareasAdminView.as_view(), name="tarea_panel"),
    path("tareas/<int:pk>/iniciar/", TareaEnProcesoView.as_view(), name="tarea_iniciar"),
    path("tareas/<int:pk>/completar/", TareaCompletarView.as_view(), name="tarea_completar"),
    path("normas/", NormasListView.as_view(), name="norma_list"),
    path("normas/<int:pk>/leer/", NormaMarcarLeidaView.as_view(), name="norma_leer"),
    path("comunicados/", ComunicadosListView.as_view(), name="comunicado_list"),
    path("comunicados/nuevo/", ComunicadoCreateView.as_view(), name="comunicado_create"),
    path("comunicados/<int:pk>/editar/", ComunicadoUpdateView.as_view(), name="comunicado_update"),
    path("comunicados/<int:pk>/leer/", ComunicadoMarcarLeidoView.as_view(), name="comunicado_leer"),
    path("comunicados/<int:pk>/lecturas/", ComunicadoLecturasView.as_view(), name="comunicado_lecturas"),
    path("personal/", PersonalListView.as_view(), name="personal_list"), path("personal/exportar/<str:formato>/", ExportarPersonalView.as_view(), name="personal_exportar"), path("personal/nuevo/", PersonalCreateView.as_view(), name="personal_create"),
    path("personal/adelantos/", AdelantoSueldoListView.as_view(), name="adelanto_sueldo_list"),
    path("personal/adelantos/nuevo/", AdelantoSueldoCreateView.as_view(), name="adelanto_sueldo_create"),
    path("personal/adelantos/<int:pk>/editar/", AdelantoSueldoUpdateView.as_view(), name="adelanto_sueldo_update"),
    path("turnos/", TurnosView.as_view(), name="turnos"), path("turnos/exportar/<str:formato>/", ExportarTurnosView.as_view(), name="turnos_exportar"),
    path("geriátricos/", GeriatricoListView.as_view(), name="geriatrico_list"),
    path("geriátricos/nuevo/", GeriatricoCreateView.as_view(), name="geriatrico_create"),
    path("geriátricos/<int:pk>/editar/", GeriatricoUpdateView.as_view(), name="geriatrico_update"),
    path("geriátricos/<int:pk>/eliminar/", GeriatricoDeleteView.as_view(), name="geriatrico_delete"),
]
