from django.contrib.auth import views as auth_views
from django.urls import path
from .views import AcercaSistemaView, ActivarCuentaView, AjusteMontoView, BackupView, CajaCierreView, CajaListView, CategoriaCajaListView, CierresCajaListView, ConfiguracionView, DescargarCierreCajaView, DescargarComprobanteView, EgresoCajaCreateView, EnviarComprobanteView, EnviarEstadoCuentaView, ExportarCajaView, ExportarPagosView, ExportarPersonalView, ExportarResidentesView, ExportarTurnosView, GenerarCuotasView, GeriatricoCreateView, GeriatricoDeleteView, GeriatricoListView, GeriatricoUpdateView, InicioView, MiPerfilView, MisTurnosView, NormaMarcarLeidaView, NormasListView, NotificacionesView, PagoDetailView, PagoListView, PanelTareasAdminView, PersonalCreateView, PersonalListView, ResidenteCreateView, ResidenteDetailView, ResidenteListView, ServiceWorkerView, TareaCompletarView, TareaEnProcesoView, TareasListView, TurnosView

urlpatterns = [
    path("service-worker.js", ServiceWorkerView.as_view(), name="service_worker"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("activar-cuenta/<uuid:token>/", ActivarCuentaView.as_view(), name="activar_cuenta"),
    path("mi-perfil/", MiPerfilView.as_view(), name="mi_perfil"),
    path("mis-turnos/", MisTurnosView.as_view(), name="mis_turnos"),
    path("notificaciones/", NotificacionesView.as_view(), name="notificaciones"),
    path("acerca-del-sistema/", AcercaSistemaView.as_view(), name="acerca_sistema"),
    path("", InicioView.as_view(), name="inicio"),
    path("residentes/", ResidenteListView.as_view(), name="residente_list"),
    path("residentes/nuevo/", ResidenteCreateView.as_view(), name="residente_create"),
    path("residentes/exportar/<str:formato>/", ExportarResidentesView.as_view(), name="residente_exportar"),
    path("residentes/<int:pk>/", ResidenteDetailView.as_view(), name="residente_detail"),
    path("pagos/", PagoListView.as_view(), name="pago_list"),
    path("pagos/exportar/<str:formato>/", ExportarPagosView.as_view(), name="pago_exportar"),
    path("pagos/generar-cuotas/", GenerarCuotasView.as_view(), name="generar_cuotas"),
    path("pagos/ajustar-montos/", AjusteMontoView.as_view(), name="ajuste_montos"),
    path("pagos/<int:pk>/", PagoDetailView.as_view(), name="pago_detail"),
    path("pagos/<int:pk>/enviar-comprobante/", EnviarComprobanteView.as_view(), name="enviar_comprobante"),
    path("pagos/<int:pk>/comprobante.pdf", DescargarComprobanteView.as_view(), name="descargar_comprobante"),
    path("residentes/<int:pk>/enviar-estado/", EnviarEstadoCuentaView.as_view(), name="enviar_estado_cuenta"),
    path("caja/", CajaListView.as_view(), name="caja_list"),
    path("caja/exportar/<str:formato>/", ExportarCajaView.as_view(), name="caja_exportar"),
    path("caja/egresos/nuevo/", EgresoCajaCreateView.as_view(), name="egreso_create"),
    path("caja/categorias/", CategoriaCajaListView.as_view(), name="categoria_caja_list"),
    path("caja/cerrar/", CajaCierreView.as_view(), name="caja_cierre"),
    path("caja/cierres/", CierresCajaListView.as_view(), name="caja_cierres"),
    path("caja/cierres/<int:pk>/pdf/", DescargarCierreCajaView.as_view(), name="caja_cierre_pdf"),
    path("configuracion/", ConfiguracionView.as_view(), name="configuracion"),
    path("configuracion/backup/", BackupView.as_view(), name="backup_generar"),
    path("tareas/", TareasListView.as_view(), name="tarea_list"),
    path("tareas/panel/", PanelTareasAdminView.as_view(), name="tarea_panel"),
    path("tareas/<int:pk>/iniciar/", TareaEnProcesoView.as_view(), name="tarea_iniciar"),
    path("tareas/<int:pk>/completar/", TareaCompletarView.as_view(), name="tarea_completar"),
    path("normas/", NormasListView.as_view(), name="norma_list"),
    path("normas/<int:pk>/leer/", NormaMarcarLeidaView.as_view(), name="norma_leer"),
    path("personal/", PersonalListView.as_view(), name="personal_list"), path("personal/exportar/<str:formato>/", ExportarPersonalView.as_view(), name="personal_exportar"), path("personal/nuevo/", PersonalCreateView.as_view(), name="personal_create"), path("turnos/", TurnosView.as_view(), name="turnos"), path("turnos/exportar/<str:formato>/", ExportarTurnosView.as_view(), name="turnos_exportar"),
    path("geriátricos/", GeriatricoListView.as_view(), name="geriatrico_list"),
    path("geriátricos/nuevo/", GeriatricoCreateView.as_view(), name="geriatrico_create"),
    path("geriátricos/<int:pk>/editar/", GeriatricoUpdateView.as_view(), name="geriatrico_update"),
    path("geriátricos/<int:pk>/eliminar/", GeriatricoDeleteView.as_view(), name="geriatrico_delete"),
]
